CREATE TABLE IF NOT EXISTS guilds (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE,
    tag VARCHAR(8) NOT NULL UNIQUE,
    description VARCHAR(255) DEFAULT '',
    level INT DEFAULT 1,
    xp BIGINT DEFAULT 0,
    max_members INT DEFAULT 10,
    bank_balance DOUBLE DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS guild_members (
    player_uuid VARCHAR(36) PRIMARY KEY,
    guild_id VARCHAR(36) NOT NULL,
    rank ENUM('LEADER', 'OFFICER', 'MEMBER', 'RECRUIT') DEFAULT 'RECRUIT',
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    contributed_xp BIGINT DEFAULT 0,
    FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guild_bank_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    guild_id VARCHAR(36) NOT NULL,
    player_uuid VARCHAR(36) NOT NULL,
    action ENUM('DEPOSIT', 'WITHDRAW') NOT NULL,
    currency VARCHAR(32) NOT NULL,
    amount DOUBLE NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guild_invites (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    guild_id VARCHAR(36) NOT NULL,
    invited_uuid VARCHAR(36) NOT NULL,
    inviter_uuid VARCHAR(36) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE
);
